name: Build release APK

on:
  workflow_dispatch:

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepGithubRelease bundleLawnWithQuickstepPlayRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: Omni Launcher unsigned release
          path: |
            build/outputs/apk/**/*.apk
            build/outputs/bundle/**/*.aab
          
